apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: "{{ .Values.metadata.name }}-{{ .Values.metadata.name }}"
  annotations:
    helm.sh/hook-weight: "30"
    metallb.universe.tf/address-pool: "{{ .Values.metadata.name }}-api-address-pool"
