apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: "{{ .Values.metadata.name }}-api-address-pool"
  namespace: metallb-system
spec:
  addresses:
{{- range .Values.platform.baremetal.apiVIPs | default (list .Values.platform.baremetal.apiVIP) }}
    - {{ . }}/{{ contains ":" . | ternary "128" "32" }}
{{- end }}
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: "{{ .Values.metadata.name }}-api-adv"
  namespace: metallb-system
spec:
  ipAddressPools:
    - "{{ .Values.metadata.name }}-api-address-pool"
