apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ .Values.pullSecret | b64enc | quote }}
metadata:
  name: assisted-deployment-pull-secret
  namespace: {{ .Values.metadata.name | quote }}
type: kubernetes.io/dockerconfigjson
