name: Build project
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Check code
        run: |
          helm lint --strict . --values install-config-example.yaml
          helm template . --values install-config-example.yaml
